name: Sync Fork

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sync Fork
        uses: TG908/fork-sync@v1.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: LearnEffinity
          base: master
          head: master
